### PR TITLE
Updated slack bot

### LINKED ISSUE #21: IFTTT check
Per @and-santos, the webhooks feature in IFTTT that we use to send messages on slack became a premium-only feature

### PR DESCRIPTION
**Pull request by seanmacb**
Updated `slack.py` to send messages with new bot

Updated `.gitignore` to exclude the webhook URL

The only thing that needs to be added in order for this to work: a file added under `configs/slack_token.txt` that contains the webhook URLs for the bot (**Note:** this will have to be changed for every successive channel that the bot is added to. If new functionality is added, that is fine, but new slack channels will require a different webhook URL)

Direct any questions on the bot to @seanmacb

### CODE REVIEW

**Review by seanmacb — COMMENTED** [review]
Reviewed, looks good. Would be nice to add the channel to `configs/slack_token.txt` and take it from the read, but that is a much lower priority issue right now

**Comment by nixnyxnyx** [comment]
Slackbot seems to work well. I'd add a Slackbot message for when strategy finishes. This really should be inside strategy itself because it's a subprocess. There used to be a slack message for strategy, so it's probably still in the code. We just need to find it and replace it with the new format.

Otherwise, for production the channel that this posts to should be #desgw-followup.

**Review by nixnyxnyx — CHANGES_REQUESTED** [review]
Look in strategy for a slackbot call or create a new one to post where the json ends up.

Production slack channel should be #desgw-followup.

**Review by nixnyxnyx — APPROVED** [review]
Update: slack call in strategy works without change.
Production slack channel should be #desgw-followup

**Pull request merged**
